
NAME= hello

CXX=arm-rpizw-g++

all: $(NAME)

$(NAME): $(NAME).o
	$(CXX) -o $(NAME) $(NAME).o

$(NAME).o: $(NAME).cpp
	$(CXX) -c $(NAME).cpp

clean:
	rm -f $(NAME) $(NAME).o

help:
	@echo "available targets:"
	@echo all
	@echo clean
	@echo help 





